version: '3.7'

services:

  qtr-fingerprints:
    build:
      context: core
      dockerfile: ./Dockerfile
    env_file: .env
    container_name: qtr-fingerprints
    working_dir: "/app/src"
    command: "python3 main.py"
    stdin_open: true
    tty: true
    ports:
      - "${ENGINE_PORT}:${ENGINE_PORT}"
    volumes:
      - "./core:/app/core"
#      - "index_data:${INDEX_DATA_DIR}"

volumes:
  index_data:
